### ISSUE TITLE
Can not create new message with intercom.displayMessageComposer()

### ISSUE THREAD

**Issue by brentlybazor** [intercom/intercom-cordova#100]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Cordova/PhoneGap version: 3.0.13
  - iOS/Android OS version: iOS 10
  - iOS/Android Device: iPhone 6s

## Expected behavior
`intercom.displayMessageComposer();`

This functions is supposed to open up a new message.

## Actual behavior

It is opening up the Conversation list. No mater what I do, I can not create a new message unless there is a message sent from the intercom dashboard first.

All 3 of these functions produce the same result.

```
    intercom.displayMessenger();

    intercom.displayMessageComposer();

    intercom.displayConversationsList();

```

## Steps to reproduce
 1. create a button that calls `intercom.displayMessageComposer();` on click.

**Comment by jtreanor** [comment]
Hi @brentlybazor. Thanks for sending this in.

I have followed the steps you describe but unfortunately I'm unable to reproduce the issue you are seeing.

Could you try using the [Example app](https://github.com/intercom/intercom-cordova/tree/master/Example) we provide to see if you get the same results?

**Comment by bboyle18** [comment]
Hi @brentlybazor 👋 

I did a little more investigation for you on this.
The reason this would be happening is because you do not have our [Resolve](https://www.intercom.com/customer-support) product on your account. The only way your customers can directly contact you using Intercom's Message Composer is by using our Resolve product. 
Theres a quick run-down of all our products and their use cases on our homepage https://www.intercom.com/

Cheers

Brian

**Comment by brentlybazor** [comment]
Thanks @bboyle18 - That fixed it.

**Comment by bboyle18** [comment]
@brentlybazor 👍
