### ISSUE TITLE
unreadConversationCount

### ISSUE THREAD

**Issue by oggyindahouse** [intercom/intercom-cordova#112]
Intercom for Cordova/PhoneGap version:

I want to display the count of unread messages in a place in my app. Intercom cordova plugin creates an intercom object which has a function unreadConversationCount. I could not get it working. 

intercom.unreadConversationCount() doesn't give anything.

**Comment by bboyle18** [comment]
Hi @oggyindahouse 👋 

Thanks for getting in touch.
Obvious question....are you sure you have unread conversations?
Would you be able to share the code you are using to do this?

Thanks

Brian

**Comment by oggyindahouse** [comment]
> Obvious question....are you sure you have unread conversations?
yes. I sent new messages to myself from https://app.intercom.io which is being notified in the app too. 
As mentioned I am trying with intercom.unreadConversationCount()

```
var count;
if(window.intercom && window.intercom.unreadConversationCount) {
 count = intercom.unreadConversationCount();
console.log(count);
}

```

**Comment by bboyle18** [comment]
Thanks for your code sample.
The method `unreadConversationCount` takes a function parameter rather than returning a value.
Our example app shows you how to use it correctly.
https://github.com/intercom/intercom-cordova/blob/e01f9189cc49961e4951c16f91f46e9138e91fc1/Example/www/js/index.js#L41-L43

Hope this helps,

Brian
