### ISSUE TITLE
Setting Secure Mode in Cordova/Ionic app

### ISSUE THREAD

**Issue by thinq4yourself** [intercom/intercom-cordova#140]
This is a question:

Please provide example of using SecureMode in Cordova. For example, what goes in `secureData{}`?

```
let hmac = crypto.createHmac('sha256', intercomSecretKey);
      hmac.update(user_id);
      let secureHash = hmac.digest('hex');

intercom.setSecureMode {
          secureHash,
          secureData {}
      }
```

For example, where would `intercom.registerIdentifiedUser()`, `intercom.updateUser()` and `intercom.registerForPush()` go?? 

Inside of `secureData{}`?

**Comment by skylerwshaw** [comment]
Hey @thinq4yourself 👋 

You pass two parameters into the `setSecureMode()` method:
```JavaScript
intercom.setSecureMode(HMAC_VALUE, USER_ATTRIBUTE_USED_TO_CALCULATE);
intercom.registerIdentifiedUser({HASH_OF_USER_CONTAINING_USERID_EMAIL_OR_BOTH});
```
e.g.
```JavaScript
intercom.setSecureMode('9b92dc8a4dbab313f0f41a4bee282f97c971c6d48d34caae2e8b0556fe5b8e26', 'user_1486733719');
intercom.registerIdentifiedUser({user_id: '1486733719', email: 'some@email.com'});
```

The secure mode secret that you use to calculate the hmac value should be kept as a server-side secret since your application can be inspected. Additionally, with Cordova you'll need to send a different hmac value for iOS and Android, since the secure mode keys are independent. You can find these keys within your App Settings panel, under the profile icon in the lower-left corner of your Intercom dashboard, within the iOS and Android settings pages.

If you have any follow-up questions, feel free to comment here or message us in Intercom using the Intercom in-app messenger within your Intercom dashboard.

**Comment by thinq4yourself** [comment]
Just to clarify one point:

In the example above, you use `user_1486733719 ` as the value for _user_id_ in `setSecureMode()`.
But just below in `registerIdentifiedUser()`, you only use `1486733719 ` for _user_id_. 

Am I missing something here in the nuance of adding `user_` prefix ?

**Comment by skylerwshaw** [comment]
@thinq4yourself The filled data was purely illustrative, showing a real string value, though this would never be hardcoded. I typed that user freehand and omitted the `user` in one example. I've edited it to show it more consistently.

**Comment by christoffer-Van** [comment]
Hey guys,

I've been trying to get this working but running into issues.

- Got my API keys for both iOS and Android
- Stored server side, and the user hash it sent to my mobile app via JSON `OpenSSL::HMAC.hexdigest('sha256', Rails.application.config_for(:intercom)[:secret_key_ios], @user.id.to_s)`
- Client side, I do this `if (this.platform.is('ios')) intercom.setSecureMode(user.intercom_user_hash_ios, JSON.stringify(user.id));`
  - I've checked I get the `success callback`, console logging the method in the success callback param
- After I do this, `intercom.registerIdentifiedUser({userId: user.id});`
- However I get an error when checking my conversations list.
<img width="323" alt="screen shot 2017-02-27 at 4 50 41 pm" src="https://cloud.githubusercontent.com/assets/8323722/23386721/f7db4c34-fd0c-11e6-95a2-82d7c3caf16c.png">

- Error goes away if I disable Secure mode from the Intercom dashboard

What am I missing?
