### ISSUE TITLE
FCM cannot be used with Phonegap Build

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#148]
## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.0

## Expected behavior
Successful Android build

## Actual behavior
Failed Android build

## Steps to reproduce
 1. Config.xml: 
plugin name="cordova-plugin-intercom" spec="3.1.0" />
preference name="intercom-android-push-type" value="FCM"/>
 2. Add google-services.json from FCM console to root folder
 3. Build with Phonegap build (https://build.phonegap.com) with CLI 6.5.0 (latest)

## Logs
FAILURE: Build failed with an exception.

* Where:
Script '/project/cordova-plugin-intercom/xxxxx-intercom.gradle' line: 22

* What went wrong:
A problem occurred evaluating script.
Plugin with id 'com.google.gms.google-services' not found.

Thanks

**Comment by jtreanor** [comment]
Hi @FabPey. Thanks for sending this in.

Does it work when using the Phonegap CLI?
Intercom relies on a [hook](https://github.com/intercom/intercom-cordova/blob/master/plugin.xml#L45) that copys `google-services.json` into the project and adds the classpath for Google services. It looks like this is not being run on Phonegap Build.

**Comment by FabPey** [comment]
Hi @jtreanor unfortunately we have no way of testing the CLI right now, we're using phonegap build exclusively, is there any chance this can be tested/fixed on your side to work with Phonegap build? Thanks!

**Comment by jtreanor** [comment]
@FabPey Unfortunately, it looks like Phonegap Build does not support hooks (see [here](https://forums.adobe.com/message/9318835#9318835)).

The hook is necessary for FCM support, but all other features will work as expected. For now, I suggest using GCM instead:
```
<preference name="intercom-android-sender-id" value="YOUR_ANDROID_SENDER_ID"/>
<preference name="intercom-android-push-type" value="GCM"/>
```

As far as I am aware, there is no other way for us to implement FCM support, so it will not work until Phone Build supports hooks.

**Comment by FabPey** [comment]
@jtreanor thank you. Are we missing out on any new intercom features/improvements when using GCM vs FCM, and have you any plans to stop supporting GCM anytime soon?

**Comment by jtreanor** [comment]
@FabPey No, there is no Intercom functionality exclusively with FCM.
We don't currently have plans to stop supporting GCM.

**Comment by FabPey** [comment]
Great, thank you.

**Comment by jtreanor** [comment]
Just a quick update here:

#152 and #153 modify the Intercom plugin to implement FCM via Gradle rather than Cordova hooks. These changes will be included in the next release.

Unfortunately, this is not quite enough to get FCM working on Phonegap Build. In order for `google-services.json` to be included in your app for FCM it is necessary to use another plugin such as https://github.com/stetro/cordova-plugin-fcm-config. A discussion on this topic is on Phonegap Build's community forums [here](https://forums.adobe.com/message/9352968).

Just to reiterate; we have done all we can to allow Intercom with FCM to work on Phonegap Build. If you come across this issue, I suggest reaching out to the Phonegap Build team directly.

I'm happy to answer any questions on this 😄
