### ISSUE TITLE
Handalling Intercom Push Notification Manually

### ISSUE THREAD

**Issue by sisodiakaran** [intercom/intercom-cordova#16]
Hi,

I have installed this plugin using `#no_play_services` method mentioned in #14 . Now I want to handle the push notification from the Intercom manually. I have registred user to recive push by method mentioned [here](https://github.com/intercom/intercom-cordova#push-notifications).

I am wondering if there is any method to manually handle Intercom Push in JAVA file.

Thanks...

**Comment by jtreanor** [comment]
Hi @sisodiakaran,

Sure, since the plugin uses Intercom for Android you can use that directly if you wish. The docs are [here](http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android).

Let me know if you have any questions :smile:

**Comment by sisodiakaran** [comment]
Thanks @jtreanor,

I am looking for a phonegap solution. I have some questions (Unable to find answers in plugin doc.)

1. What will be the process/functions to register for Intercom Push for Android?
* If I registered successfully, how can I handle the push notification from the Phongap Plugin?
* Is there any fallback function for register for Intercom Push?
* What if I already registered my user on Intercom using `intercom.registerIdentifiedUser()` function?
* How to deregister from the Intercom Push on logout?

Thanks...

**Comment by sisodiakaran** [comment]
@jtreanor Any clue?

**Comment by harkin** [comment]
@sisodiakaran James is out of the office for the week, I'll try to help (I'm one of the Android engineers at Intercom but I'm not very au fait with phonegap I'm afraid)

To register you'll need to call 'setupGcm' with your registration token. 

If it's successful then you don't need to do anything yourself to get a push to display, the Intercom library handles all of that for you. In order to get correct behaviour when someone taps on a push notification to open your app you'll need to call `openGCMMessage` in the part of your app that is hit first when it launches.

I'm not sure what you mean by 3; is it some callback in case registration fails? 

You need to have a registered user before you register for push with Intercom.

You can call `reset` on logout. This will clear everything, not just push related things and you will need to register a new user before you can update anything or log events again.

**Comment by sisodiakaran** [comment]
Thanks @harkin, what do you mean by `registration token` is it Sender Id of GCM ( Project ID of Google API Project)?

**Comment by sisodiakaran** [comment]
I used `setupGCM` function and still not receiving any push on direct message. Here is my code to register a user:

```
// Register Intercom User
intercom.registerIdentifiedUser({email: <my user email>}, function(resp){
    console.log(resp); // It gives 'OK'
                                    
    // Register for Intercom Push
    intercom.setupGCM(<my_sender_id>, function(resp){
            console.log(resp); // It gives 'OK'
        }, function(err) {
            console.error(err);
        });
    }, function(err) {
        console.error(err);
    });
```

**Comment by sisodiakaran** [comment]
Any clue @jtreanor?

**Comment by slorber** [comment]
@sisodiakaran according to what I see in the code:
`setupGCM: function(regId, success, error)`
You have to provide a GCM registrationId, and not a SenderId

**Comment by slorber** [comment]
@jtreanor I'm also interested in the solution if this permits to receive Intercom + app pushes without using the fork.

I've tried something like this:

```
            intercom.registerIdentifiedUser(intercomData,function() {
                var push = PushNotification.init({
                    "android": {"senderID": "xxx"},
                    "ios": {},
                    "windows": {}
                });

                push.on('registration', function(data) {
                    intercom.registerForPush("xxx");
                    intercom.setupGCM(data.registrationId);
                });
            });
```

But I'm still unable to receive push notifications of Intercom. Logcat shows that no GCM message is received when I reply to my test user on Intercom.

Is there a way to debug this on intercom desktop app? I did not see any "registrationId" or thing like that in my user dashboard but this could be useful to see if intercom has the right registrationId in its DB.

**Comment by jtreanor** [comment]
Sorry for the very delayed response on this. First, to answer @sisodiakaran questions:

> What will be the process/functions to register for Intercom Push for Android?

This code is all you need for push to work:

```
intercom.registerForPush('sender_id');
intercom.registerIdentifiedUser({email: <my user email>};
```

> If I registered successfully, how can I handle the push notification from the Phongap Plugin?

Unfortunately, you must use our fork of the PushPlugin as outlined [here](https://github.com/intercom/intercom-cordova#push-notifications). This is because the plugin uses very outdated methods so we had to work around some issues.

> Is there any fallback function for register for Intercom Push?

I'm not sure what you mean by this.

> What if I already registered my user on Intercom using intercom.registerIdentifiedUser() function?

It should work fine if a user is already registered.

> How to deregister from the Intercom Push on logout?

This happens automatically when you call `intercom.reset()`.


I hope this answers your questions.

@slorber Can you also try the code snippet above?

**Comment by slorber** [comment]
@jtreanor unfortunatly I can't use your fork as the plugin version you patched has a bug that I recently fixed (https://github.com/phonegap/phonegap-plugin-push/issues/101)

According to what I see in your fix (https://github.com/intercom/PushPlugin/commit/bddd917b3f273cf7e829b9286f7946ac2a575f14) your code only fixes the "reception" of the push messages.

Still, even if not displaying them appropriatelely, my mobile should be able to receive the pushs (and they should be displayed in logcat). It is not the case.

I've tried to use : 
```
            intercom.registerIdentifiedUser({userId: userId});
            intercom.registerForPush("345598564729");
```

I get the following logs:

```
I/Intercom-Android(13698): INFORMATION: Intercom has already been initialized
I/Intercom-Android(13698): INFORMATION: The Uri passed into the method openGCMMessage was null.
I/dalvikvm(13698): Could not find method java.nio.file.Files.newOutputStream, referenced from method io.intercom.okio.Okio.sink
I/dalvikvm(13698): Could not find method java.nio.file.Files.newInputStream, referenced from method io.intercom.okio.Okio.source
I/Intercom-Android(13698): INFORMATION: Successfully registered or updated user
I/Intercom-Android(13698): INFORMATION: Successfully reset user. To resume communicating with Intercom, you can register a user
I/chromium(13698): [INFO:CONSOLE(173)] "intercomLogout", source: file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js (173)
I/Intercom-Android(13698): INFORMATION: Can't create GCM message we have no user identity. This can be caused by messages being sent to a logged out user.
I/chromium(13698): [INFO:CONSOLE(173)] "intercomLogin", source: file:///android_asset/www/plugins/cordova-plugin-console/www/console-via-logger.js (173)
I/Intercom-Android(13698): INFORMATION: Successfully registered or updated user
I/Intercom-Android(13698): INFORMATION: Successfully registered or updated user
```


Remember my special integration (#18) where I call reset() and then registerUser(). 
I tried to remove the call to reset() but but it did not change much.



Notice that I can see my registrationId is received, and `sendRegistrationIdToBackend` is called directly (not in background). So I may expect that Intercom has received my registrationId. Note in Intercom settings I did enable Intercom GCM and added my ApiKey.

I tried to converse with my user on Intercom, and my mobile did not receive the push (I mean: nothing happens in logcat at all).

----------------------------------------------------------

Here are some things I'm not sure of:

- setUpPush takes a `senderId` param. But as far as I can see, as I don't register in background, this param is never used at all, and not sent to your backend. Is this normal?

- Should the param senderId be the senderId of my usual backend? I wasn't sure. For me Intercom != my backend, so I would have expected Intercom to provide me its own senderId (but was not able to find anything about that on my backend.

- What's the point of setupGCM then?


----------------------------------------------------

If that can help, here's my test Intercom user:

https://app.intercom.io/a/apps/f91b67651d379de0e5cd522eb3681d3452d94ab6/users/530b542782521e5fe7004e47

You may be able to check whether or not you have received a registrationId for that user, and if push attempts has been done on your side.

**Comment by sisodiakaran** [comment]
@jtreanor,

> Unfortunately, you must use our fork of the PushPlugin as outlined here. This is because the plugin uses very outdated methods so we had to work around some issues.

 I am not using `PushPlugin` in my app at all I have integrated `CordovaPush` by `Realtime.co`.

> I'm not sure what you mean by this.

I mean if `registerForPush` function failed by any mean, so what will be the callback? Where I can specify the callback methods?

**Comment by jtreanor** [comment]
Sorry for the delay here @slorber and @sisodiakaran.

Clearly we have improvements to make in our Cordova push/GCM integration.

@slorber:

In the example shown, a GCM push message is actually received but it can't be shown because you have called `reset()`. I'm not sure why it would be broken when you don't call reset.

The `sender_id` that you pass to `intercom.registerForPush(..)` should be copied from your Google Developer Console. This is never sent to Intercom, we simply use it to get a registration ID.

The purpose of `setupGCM` is to allow you to pass a `registration_id` instead of a `sender_id` if you prefer.

Thanks for the detail, I realise that this is not as simple as it could be.

@sisodiakaran:

Because of the many assumptions that push plugins for Cordova currently make, `CordovaPush` and others will have issues with Intercom out of the box. We are working on better ways to work around this.

There is no callback for `registerForPush`. If it is successful, push will work with Intercom. If not, it keeps retrying until it succeeds. There is not much you could do to respond to it anyway.

**Comment by jtreanor** [comment]
Closing as this is as complete as is possible right now.
