### ISSUE TITLE
3.1.2 installation fail due to pod command on iOs...

### ISSUE THREAD

**Issue by PRotig** [intercom/intercom-cordova#169]
Hello guys, 
Me again... (still not working on Android :(...) still looking to make it work. Seens the 3.1.2, can't make it on iOs... 
By the way, my customers like my Intercom integration 👍 👍 👍 
We can do this ! 
Thanks for your help.

## Version info
Intercom for Cordova/PhoneGap version: 3.1.2 (but install do not work on ios)
Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.1 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 8.2.1 Build version 8C1002

## Expected behavior
Add Intercom plugin for my ionic app

## Actual behavior
Install fails :(

## Steps to reproduce
 1. `cordova plugin add cordova-plugin-intercom --save`

## Logs
```
Fetching plugin "cordova-plugin-intercom" via npm
Installing "cordova-plugin-intercom" for android
Subproject Path: CordovaLib
Installing "cordova-plugin-intercom" for ios
Failed to install 'cordova-plugin-intercom':Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/*********************/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Error: pod: Command failed with exit code 1

```

**Comment by jtreanor** [comment]
@PRotig We're glad that you and your customers are happy with Intercom 😄

However, right now it does not appear that this or https://github.com/intercom/intercom-cordova/issues/165 are issues with the Cordova plugin, but with your specific integration.

Since you have persistent issues, it would be much easier to resolve your issues by discussing the specifics of your integration directly with our support team. You can send a message in through he Messenger on [intercom.com](https://www.intercom.com).

P.S. This particular problem should be resolved by running `pod repo update`.
