### ISSUE TITLE
Problem with translations & cannot exit window on iOS

### ISSUE THREAD

**Issue by mazengharbi** [intercom/intercom-cordova#190]
Hello there,

When I open a conversation on my **iOS** app, translations aren't ready and exit button doesn't display. There is no problem with Android build

## Version info
  - Intercom for Cordova/PhoneGap version: 3.2.2
  - iOS OS version: 
  - iOS  Device: iPhone 5 / 6 / ...

## Actual behavior

![Intercom on iOS](http://i.imgur.com/Tqr3MDK.png)

As you can see, text aren't translated and there is no way to close actual window

**Comment by bboyle18** [comment]
Hi @mazengharbi 👋 

The problem is is that `Intercom.bundle` which contains all Intercom's images and strings is not being loaded correctly.
Can you try the steps [outlined here](https://github.com/intercom/intercom-cordova/issues/161#issuecomment-290089078)?
Theres sometimes issues with Cordova that requires these steps to be completed.

Let me know you get on.

Brian

**Comment by mazengharbi** [comment]
Hey, 

Nice one, everythings works perfectly now! Thank you
