### ISSUE TITLE
Error building for IOS (framework not found IOSurface for architecture armv7)

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#218]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Cordova/PhoneGap version: 4.1.0
  - iOS/Android OS version: iOS 8 and 9
  - iOS/Android Device:

## Expected behavior
Building with phonegap CLI (latest cordova-ios 4.5.3) - works perfect with intercom plugin 4.0.0

## Actual behavior
When switching to v 4.1.0 of intercom plugin, iOS builds fail with Error 65 - The reason for swtiching to 4.1.0 is the need to use intercom.logout() function which is introduced in this version.

## Steps to reproduce
 1. Upgrade intercom plugin to 4.1.0.
 2. Build for IOS using phonegap CLI and xCode 8.2.1
 3. PS: It works again as soon as I downgrade to v 4.0.0 of intercom plugin - tried building for iOS 8 and 9 - both fail.

## Logs
ld: framework not found IOSurface for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[...]

The following build commands failed:
	Ld /Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxxx-gwercdifwkvkztawipkqwzeychas/Build/Intermediates/ArchiveIntermediates/xxxxx/IntermediateBuildFilesPath/xxxxx.build/Debug-iphoneos/xxxxx.build/Objects-normal/armv7/xxxxx normal armv7
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/xxxxx/documents/apps/phonegap/platforms/ios/cordova/build-debug.xcconfig,-workspace,xxxxx.xcworkspace,-scheme,xxxxx,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,xxxxx.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/xxxxx/documents/apps/phonegap/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/xxxxx/documents/apps/phonegap/platforms/ios/build/sharedpch

**Comment by skylerwshaw** [comment]
Building with xCode 9 will resolve this issue.

You are seeing this error because Cordova 4.1.0 sources 4.1.x of the iOS SDK. 4.1.3 is the first version of Intercom that was built using Xcode 9. We must build with Xcode 9 in order to fully support iPhone X and iOS 11.

A quick search suggests there may be a possible workaround for the issue [here](https://stackoverflow.com/a/46483043).

As there is nothing we can do to fix this, I'm closing the issue.

Ref: https://github.com/intercom/intercom-ios/issues/327#issuecomment-340724951
