### ISSUE TITLE
cordova-android@7.0.0

### ISSUE THREAD

**Issue by jpike88** [intercom/intercom-cordova#231]
I needed to perform the following fixes to get cordova-android@7.0.0 to work (using cordova@8.0.0)

https://github.com/streaka/intercom-cordova/commit/93ea90b30c1a2676d9fbee4cc07e69be44732b8b

https://github.com/streaka/intercom-cordova/commit/37dafc3caa98aa9e3a864d455c8f5a74cf1dc420

**Comment by amrsh** [comment]
+1. Cannot build android, it is looking for platforms/config.xml (No such file or directory)

**Comment by gcremalin** [comment]
+1 on this. @jpike88 is everything woking normally with those 2 fixes applied?

**Comment by jpike88** [comment]
Yep. Works good. Had to get the plugin into the root directory though, no idea why they chose that structure as it makes forking a PITA.

**Comment by skylerwshaw** [comment]
Fixed in [5.0.0](https://github.com/intercom/intercom-cordova/releases/tag/5.0.0), released today.

We've changed the directory structure per the breaking changes made in Cordova Android 7.0.0 detailed here: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

**Comment by Upperfoot** [comment]
@skylerwshaw What was the exact issue of the FCM push notifications not being received? As I'll need to backport the fixes as Cordova Android 7.0.0 isn't supported across all plugins yet.

**Comment by Upperfoot** [comment]
@skylerwshaw Also did a test on this, and GCM notifications don't work either after switching the Push Type.

**Comment by skylerwshaw** [comment]
@Upperfoot The primary push issue with using our <5.0.0 plugins and Cordova Android 7.0.0 was twofold. If specifying GCM as the push type in the config.xml, we had a convenience preference to add the sender_id within config.xml as well. This ceased to function with Cordova Android 7.0.0 due to a change in how [this line](https://github.com/intercom/intercom-cordova/blob/9ba0070d4ebdade22c42a597e28ca789b44ac1c0/intercom-plugin/src/android/IntercomBridge.java#L75) is handled by Cordova. With FCM specified, we utilized the google-services.json file placed at the root of the project. This broke because of the directory structure changes cited in the announcement above. 

Using Intercom Cordova 5.0.1 or higher permits building with Cordova Android 7 and works with FCM push by specifying so in config.xml and adding the google-services.json file into the root of the project.

The issue of FCM push not being received **when you are using FCM push providers in addition to this plugin** remains and will be worked on soon.

**Comment by Upperfoot** [comment]
@skylerwshaw Thanks Skyler, I believe our issue is the latter, we have several providers making use of FCM, could an interim solution be that we are given a method to send our own Push Token?

We have half of our user base unable to receive Intercom push notifications (Android), so if we send them a message they are not prompted to open it as they would if they had Push notifications, making things quite difficult in terms of response times.
