### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0

### ISSUE THREAD

**Issue by kanji-keraliya** [intercom/intercom-cordova#244]
Installing "cordova-plugin-intercom" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.3.0, failed version requirement: >=7.0.0

Skipping 'cordova-plugin-intercom' for android
Installing "cordova-plugin-intercom" for ios

Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.4.0, failed version requirement: >=4.5.4
Skipping 'cordova-plugin-intercom' for ios
Adding cordova-plugin-intercom to package.json

**Comment by kanji-keraliya** [comment]
also when change android version 7.0.0 and install latest plugin and npm. application stopped working and showing only white blank screen

**Comment by bboyle18** [comment]
Hi @kanji-keraliya 👋 
Thanks for getting in touch!

The latest version of the Intercom plugin for Cordova requires Cordova 7.0.0 because there were breaking changes in this release that we needed to support. Details are here https://github.com/intercom/intercom-cordova/releases/tag/5.0.0

With regards to your issue of only seeing a white blank screen, are there any logs you can provide us with? It would also be helpful to see a GIF/video of this in action or anything else that you feel might help us investigate this issue.

Thanks

Brian

**Comment by ronocod** [comment]
We are moving all our issues support to our [Intercom Developer Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). If you bump into further problems or need updates on this issue, just start a conversation using Intercom there and it will be immediately routed to our Customer Support Engineers.
