### ISSUE TITLE
Allow appId / apiKey to be configured at runtime

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-cordova#29]
Our server architecture cares for giving out necessary appId / apiKeys to the client. The problem with this plugin is that static keys must be given through configuration.

I think it would be extremely helpful to have `intercom.init` function available (in Javascript) where we can pass these details. Keys are never static, especially in a DTAP environment.

**Comment by santervo** [comment]
+1

Current configuration model does not work with separate production/testing environments

**Comment by jtreanor** [comment]
Thanks @rubenstolk and @santervo.

Unfortunately, this is not very straightforward to add. Changing app at runtime can lead to unexpected behaviour and is not currently possible with Intercom for Android.

The best solution we have right now is to provide different keys on your config.xml for production and testing environments.

**Comment by santervo** [comment]
@jtreanor separate keys would be enough for my case at least

**Comment by santervo** [comment]
@jtreanor Are there any plans for supporting separate keys for production and testing?

**Comment by jtreanor** [comment]
Hi @santervo,

How do you configure your production and testing environments for Cordova? The low tech solution would be to swap keys in your config.xml as you swap environments.

You are welcome to open a PR or suggest how you would like this feature to work.

**Comment by santervo** [comment]
@jtreanor 

Configuring separate production and testing env is an issue in cordova (there's no built in mechanism). That's why separate keys in config.xml would not probably work (it's not known which environment is used). So in general I think it would be best to not configure plugins in config.xml, but in runtime.

I've done the configuration for different environments in javascript side (generate configuration in build process). So the solution @rubenstolk mentioned would be ideal for me (intercom.init function). It would not be required to *change* the app_id in runtime. Just the possibility to set it up the first time programmatically. It could raise exception if trying to set it up again.

**Comment by rubenstolk** [comment]
I totally agree that Cordova doesn't provide a good system for managing different environments, therefore it's much better to allow injecting the keys at run time as well. In my architecture keys are managed from a configuration management api and the config.xml is not sustainable...

**Comment by jtreanor** [comment]
@santervo @rubenstolk

An Intercom init function may not work as you expect primarily because Intercom expects to be initialised early in the app's lifecycle.

Here is one approach we could take:

Allow `intercom-debug-app-id`, `intercom-debug-ios-api-key` and `intercom-debug-android-api-key` to optionally be defined in your `config.xml` in addition to the existing keys. If the app is running in debug mode, Intercom will use these new values, otherwise it would use the existing ones.

Would this address the problem you are facing?

**Comment by rubenstolk** [comment]
No it would not because we use full builds in beta where the only difference would have to be this key. Our api stores the intercom app id and key, so it would receive those prior to the intercom init...

**Comment by rubenstolk** [comment]
Hi @jtreanor I think this can be solved using https://github.com/intercom/intercom-cordova/pull/39. Doesn't change any existing functionality but adds the possibility to not provide the keys through config but at a later stage after the app has started.

This also helps for cases where you only want to initialize Intercom at a later stage in an app, for instance when the user has logged in.

**Comment by rubenstolk** [comment]
Hi @jtreanor sorry to keep bother but perhaps it would be good if you can update me if this is on your roadmap or not so that I can plan whether we should start a fork for our purposes or not.

**Comment by jtreanor** [comment]
@rubenstolk I will be looking at this soon. As stated previously #39 may cause use data issues so we must verify it carefully.

**Comment by rubenstolk** [comment]
@jtreanor any expectations for this?

**Comment by rubenstolk** [comment]
@jtreanor ping

**Comment by jtreanor** [comment]
Hi @rubenstolk,

Sorry for not responding sooner. After considering this carefully, unfortunately this is not something we will be supporting in the plugin at this time. Configuration at runtime is not fully supported in our native library due to platform limitations so for now at least, this will not be possible.

**Comment by NipunKalra** [comment]
Hi @jtreanor,
I know this is question was closed more than a year ago, but is it still the same or can we configure the app id at runtime. I have a situation where I want to use 2 Intercom app id in the same app.
Open for more suggestions.

Cheers
Nipun

**Comment by NipunKalra** [comment]
Thank you @jtreanor  for replying.
By any chance is there a way I can use two separate AppIds for Intercom in the same app?

**Comment by jtreanor** [comment]
@NipunKalra Not at the same time. You will need to switch that in config.xml.
