### ISSUE TITLE
Name in first auto message after registerIdentifiedUser

### ISSUE THREAD

**Issue by WilliamPanasiuk** [intercom/intercom-cordova#47]
## Version info
  - Intercom for Cordova/PhoneGap version: 1.1.4

## Expected behavior
First auto message

> Type is User   First Seen has any value

`First name` as name

## Actual behavior
First auto message

> Type is User   First Seen has any value

`First name` is "**there**" no name

## Steps to reproduce
intercom.registerIdentifiedUser({ 
email: email
})
intercom.updateUser({
email: email,
name: name
});

**Comment by DaleCantwell** [comment]
Hi @WilliamPanasiuk. The issue here is that the message matched before the users name managed to update. We are aware of the issues that can cause with auto messages and we will think of possible long term solutions. In the meantime a possible solution is to add another filter NAME has any value. This will only match one the user has been seen and the name has been set.
Thanks for reporting the issue.
